### ISSUE TITLE
Cant enable addon

### ISSUE THREAD

**Issue by coobenguy** [blackears/godot_volume_layers#1]
Godot 4.2.1

When trying to enable the addon you get 

"res://addons/volume_layered_shader/volume_layered_shader_addon.gd:9 - Parse Error: Preload file "res://addons/volume_layered_shader/art/volume_layered.svg" does not exist.
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://addons/volume_layered_shader/volume_layered_shader_addon.gd" with error "Parse error". (User)"

Upon further inspection, the addon doesnt even have an "art" folder to find the file in.

**Comment by blackears** [comment]
I've updated the 1.0.1 release.  The art directory should be there now.
