### ISSUE TITLE
Noisy visual with the iguana demo

### ISSUE THREAD

**Issue by kimjohn1** [blackears/godot_volume_layers#2]
I'm a graduate student working on a project that uses scientific visualization, considering using Godot to visualize volumetric data being generated by High Energy Physics simulation.  I tried following your Volume Viewer for Godot video and am able to get the image of an iguana skull, but the visual includes some sort of interference (screen capture attached).  The skull image is visible (great visual) and appears to respond correctly to the Volume Layer adjustment entries (very cool), but I need help figuring out how to eliminate the tiny dancing squares.  Please let me know if you have any ideas.
Thanks,
Kim Peterson
![noisy_iguana](https://github.com/blackears/godot_volume_layers/assets/61957753/5e1dbf61-d444-4fa1-8c77-62c8b24adee0)

**Comment by blackears** [comment]
I've not seen anything like that before and am not sure what may be causing it.  It looks like some sort of memory corruption with your graphics card.  What OS and graphics card are you using?  Have you tried this on a different computer?  Also, have you tried Forward vs Mobile vs Compatibilty modes?  You might also want to try updating your graphics drivers.  You could also try moving the shader sliders to see if some configurations give you a clear picture.

Edit:
Just noticed you're in orthogonal mode.  Have you tried a perspective camera view?

**Comment by kimjohn1** [comment]
I have been using 2 different computers, Windows 11 and Linux (Mint 21.1).  Both computers have RTX4090 with up to date drivers.  I have tried all the perspective views.  Forward and Mobil Modes (Compatibility Mode shows the noise, but no Iguana).  I've adjusted the slider controls.  All of that (other than Compatibility Mode) has no effect.

I installed Godot_Volume_Layers in the Windows machine by downloading the zip file from the github site.  Godot was installed on the Linux machine using Software Manager.  Both installations are version 4.2.1.  I retrieved Blender from the Blender website for each machine.  They both indicate Blender version 4.0.2.  Godot Volume Layers is version 1.0.2.

I notice that when I run the project I get no image, just a plain dark grey screen that opens up.  Should the project run and produce a visual?

Today is the first time I have ever installed Godot, so the chances of me making a mistake or leaving something important undone seem pretty high as I followed the video and installed the Iguana Demo Project.  I'll look around for some other Godot v4 demo project and see if I can verify that I'm doing the installation and project setup right.

Kim

**Comment by blackears** [comment]
I just opened the project, and am getting the same issues.  I'm not sure why - everything was working fine when I last touched it a few months ago.  I'll have a look at it tomorrow.

**Comment by blackears** [comment]
I've pushed an update.  This should fix the issue.  The color variable was not being explicitly initialized which is what was causing problems based on the system.

**Comment by kimjohn1** [comment]
Perfect.  I confirm the issue is fixed:
<img width="549" alt="Screenshot 2024-02-28" src="https://github.com/blackears/godot_volume_layers/assets/61957753/01388ae0-80da-47df-b42c-4e10db3c6230">
