### ISSUE TITLE
auto re-loading the image file

### ISSUE THREAD

**Issue by kimjohn1** [blackears/godot_volume_layers#4]
I have the Volume Layer addon working in Godot VR (using Quest 3) on my Linux machine:

A video showing 5 minutes of me floating around the wakefield; https://youtu.be/-INQylQH0qY

I will modify the Laser Wakefield simulation program to launch Godot and run the visualization project, and I need a way to re-load the project's image source file every time the simulation generates an output, so the VR visualization shows the progress of the simulation in real time.

Is the image file re-loaded automatically as the project is running, and if not is there a feature that can be set or a script that can be used to do that?

**Comment by blackears** [comment]
The ZippedImageArchiveCpuTexture3D won't automatically detect if the zip file changes, but you can monitor the file yourself and create a new ZippedImageArchiveCpuTexture3D when it does change.  Then just assign the new Texture3D to the VolumeLayeredShader.

The code could be modified to handle live data, but it sounds like you are dumping your data to a zip archive and then loading that, so the above method should work the best.
